title: Asus TDP
type: container
tags: [hide-title]
hint: >-
  Uses the interface of Armory Crate to set the TDP of the device.
children:
  tdp:
    type: int
    title: TDP
    hint: >-
      Average TDP Target.

      Sets the values STAMP and Skin Power Limit to it without boost.
      With boost, it sets the fast value to 53/30*tdp and the slow value to 43/30*tdp.
      Boost is recommended for desktop use.

    min: 5
    max: 30
    step: 1
    default: 15
    unit: W
  boost:
    type: bool
    title: TDP Boost
    default: True
    hint: >-
      Allows the device to boost by setting appropriate slow and fast TDPs.

  fan:
    type: mode
    title: Custom Fan Curve
    hint: >-
      Allows you to set a custom fan curve.
    default: disabled
    modes:
      disabled:
        type: container
        title: Disabled
        hint: >-
          Lets the device manage the fan curve on its own.
      manual:
        type: container
        title: Manual [BETA]
        tags: [ non-essential ]
        children:

          st30: &speed_template
            title: 30C
            hint: Sets the speed at the named temperature.
            tags: [slim]
            type: int
            min: 0
            default: 5
            max: 100
            step: 2
            unit: "%"
            
          st40:
            <<: *speed_template
            title: 40C
            default: 10
          st50:
            <<: *speed_template
            title: 50C
            default: 20
          st60:
            <<: *speed_template
            title: 60C
            default: 35
          st70:
            <<: *speed_template
            title: 70C
            default: 55
          st80:
            <<: *speed_template
            title: 80C
            default: 75
          st90:
            <<: *speed_template
            title: 90C
            default: 75
          st100:
            <<: *speed_template
            title: 100C
            default: 75
            
          reset:
            title: Restore Default
            type: action
            hint: >-
              Restore a default sane fan curve.

          disclaimer:
            title: Fan Curve Limitation
            type: display
            default: >-
              Asus hardware limits the minimum fan curve depending on TDP.
              The minimums are 25%, 50%, and 75% for low, middle, and high TDPs.