title: Asus TDP
type: container
tags: [hide-title]
hint: >-
  Uses the interface of Armory Crate to set the TDP of the device.
children:
  tdp_v2:
    type: mode
    title: TDP Mode
    default: balanced
    modes:
      quiet:
        type: container
        title: Silent
        unit: 
      balanced:
        type: container
        title: Performance
        unit: 
      performance:
        type: container
        title: Turbo
        unit: 
      custom:
        type: container
        title: Custom
        unit: â†’ 25/30W
        children:
          tdp:
            type: int
            title: TDP
            hint: >-
              Average TDP Target.
              TDP Boost is recommended for desktop use and does not affect gaming.

            min: 0
            max: 30
            step: 1
            default: 30
            unit: W
          boost:
            type: bool
            title: TDP Boost
            default: True
            hint: >-
              Allows the device to temporarily boost by setting appropriate slow and fast TDPs.
  
  sys_tdp:
    type: display
    title: " "
    tags: []

  cycle_tdp:
    type: bool
    title: Change TDP with View+Y
    tags: [ non-essential ]
    hint: >-
      Allows you to cycle through TDP modes with the View+Y key combination.
      Recommended to use with ROG Swap, as the View button will be muted to games.
    default: False

  fan:
    type: mode
    title: Custom Fan Curve
    hint: >-
      Allows you to set a custom fan curve.
    default: disabled
    modes:
      disabled:
        type: container
        title: Disabled
        hint: >-
          Lets the device manage the fan curve on its own.
      manual:
        type: container
        title: Manual
        tags: [ non-essential ]
        children:

          st30: &speed_template
            title: 30C
            hint: Sets the speed at the named temperature.
            tags: [slim]
            type: int
            min: 0
            default: 5
            max: 100
            step: 2
            unit: "%"
            
          st40:
            <<: *speed_template
            title: 40C
            default: 10
          st50:
            <<: *speed_template
            title: 50C
            default: 20
          st60:
            <<: *speed_template
            title: 60C
            default: 35
          st70:
            <<: *speed_template
            title: 70C
            default: 55
          st80:
            <<: *speed_template
            title: 80C
            default: 75
          st90:
            <<: *speed_template
            title: 90C
            default: 75
          st100:
            <<: *speed_template
            title: 100C
            default: 75
            
          reset:
            title: Restore Default
            type: action
            hint: >-
              Restore a default sane fan curve.

          disclaimer:
            title: Fan Curve Limitation
            type: display
            default: >-
              Asus hardware limits the minimum fan curve depending on TDP mode.

  charge_limit:
    type: multiple
    title: Charge Limit (%)
    tags: [ non-essential, ordinal ]
    hint: >-
      Applies a charge limit to the battery, 75% and up.
    options:
      p70: 70%
      p80: 80%
      p85: 85%
      p90: 90%
      p95: 95%
      disabled: Unset
    default: disabled

  extreme_standby:
    type: multiple
    title: Extreme Standby Mode
    tags: [ non-essential, ordinal ]
    options:
      disabled: Disabled
      enabled: Enabled
    default: disabled
    hint: >-
      Lowers the power consumption of the device from 4% to 1% overnight.
      Active only on battery. Turns off the power light and the controller 
      requires longer to wake up.