title: Asus TDP
type: container
tags: [hide-title]
hint: >-
  Uses the interface of Armory Crate to set the TDP of the device.
children:
  tdp:
    type: int
    title: TDP
    hint: >-
      Average TDP Target.

      Sets the values STAMP and Skin Power Limit to it without boost.
      With boost, it sets the fast value to 53/30*tdp and the slow value to 43/30*tdp.
      Boost is recommended for desktop use.

    min: 5
    max: 30
    step: 1
    default: 15
    unit: W
  boost:
    type: bool
    title: TDP Boost
    default: True
    hint: >-
      Allows the device to boost by setting appropriate slow and fast TDPs.

  fan:
    type: mode
    title: Custom Fan Curve
    hint: >-
      Allows you to set a custom fan curve.
    default: disabled
    modes:
      disabled:
        type: container
        title: Disabled
        hint: >-
          Lets the device manage the fan curve on its own.
      manual:
        type: container
        title: Manual
        tags: [ non-essential ]
        children:

          st30: &speed_template
            title: 30C
            hint: Sets the speed at the named temperature.
            tags: [slim]
            type: int
            min: 0
            default: 5
            max: 100
            step: 2
            unit: "%"
            
          st40:
            <<: *speed_template
            title: 40C
            default: 10
          st50:
            <<: *speed_template
            title: 50C
            default: 20
          st60:
            <<: *speed_template
            title: 60C
            default: 35
          st70:
            <<: *speed_template
            title: 70C
            default: 55
          st80:
            <<: *speed_template
            title: 80C
            default: 75
          st90:
            <<: *speed_template
            title: 90C
            default: 75
          st100:
            <<: *speed_template
            title: 100C
            default: 75
            
          reset:
            title: Restore Default
            type: action
            hint: >-
              Restore a default sane fan curve.

          disclaimer:
            title: Fan Curve Limitation
            type: display
            default: >-
              Asus hardware limits the minimum fan curve depending on TDP.
              The minimums are 25%, 50%, and 75% for low, medium, and high TDPs.

  charge_limit:
    type: multiple
    title: Charge Limit (%)
    tags: [ non-essential ]
    hint: >-
      Applies a charge limit to the battery, 75% and up.
    options:
      disabled: Disabled
      p65: 65%
      p70: 70%
      p80: 80%
      p85: 85%
      p90: 90%
      p95: 95%
    default: disabled
  
  disclaimer:
    title: Sleep Bug
    type: display
    tags: [ non-essential ]
    default: >-
      There is an Asus kernel/BIOS bug that will sometimes limit TDP to 10W
      after sleep.
      As the kernel driver is used, this is unfixable from within
      Handheld Daemon (currently investigated).
      As an alternative, use SimpleDeckyTDP with RyzenAdj after
      disabling TDP controls from "Settings".
