title: Lenovo TDP
type: container
hint: >-
  Uses the interface of Legion Space to set the TDP of the device.
children:
  tdp:
    type: mode
    title: TDP Mode
    modes:
      quiet:
        type: container
        title: Quiet (8W)
      balanced:
        type: container
        title: Balanced (15W)
      performance:
        type: container
        title: Performance (20W)
      custom:
        type: container
        title: Custom (up to 25-30W)
        children:
          tdp:
            type: int
            title: TDP
            hint: >-
              Maximum TDP in steady state. 
              Sets STAMP, Skin Power Limit to it (steady state).
              If boost is enabled, interpolates slow and fast TDPs based
              on those provided by Lenovo.
              If disabled, it sets the Slow limit equal to TDP and the Fast
              limit to +2W.
              Boost is recommended for desktop use.

            tags: [advanced]
            min: 0
            max: 30
            step: 1
            unit: W
          boost:
            type: bool
            title: Boost
            default: True
            hint: >-
              Allows the device to boost by setting appropriate slow and fast TDPs.
  
  ffss:
    type: bool
    title: Set Fan to Full Speed

  fan:
    type: mode
    title: Custom Fan Curve
    hint: >-
      Allows you to set a custom fan curve. This fan curve is only officially
      supported on custom mode, but you can nevertheless use it in other power
      modes at your own risk.

      This fan curve needs to be reapplied every time you switch TDP modes.
      Adjustor will automatically apply it for changes made through the UI
      but not with Legion L + Y.
    default: disabled
    modes:
      disabled:
        type: container
        title: Disabled
        hint: >-
          Lets Legion GO manage the curve on its own. Setting this option will cause
          a mode change to reset the fan curve.
      manual:
        type: container
        title: Manual
        children:
          apply:
            title: Apply Fan Curve
            type: action
            hint: >-
              Reapplies the fan curve below if it got reset.
          
          status:
            title: Fan Curve Status
            type: display
            # For translation
            choices:
              startup: Unknown
              not-set: Not Set
              set: Set


          st10: &speed_template
            title: 10C
            hint: Sets the speed at the named temperature.
            tags: [slim]
            type: int
            min: 0
            smin: 44
            max: 115
            step: 2
            unit: "%"
          
          st20:
            <<: *speed_template
            title: 20C
            smin: 48
          st30:
            <<: *speed_template
            title: 30C
            smin: 55
          st40:
            <<: *speed_template
            title: 40C
            smin: 60
          st50:
            <<: *speed_template
            title: 50C
            smin: 71
          st60:
            <<: *speed_template
            title: 60C
            smin: 79
          st70:
            <<: *speed_template
            title: 70C
            smin: 87
          st80:
            <<: *speed_template
            title: 80C
            smin: 87
          st90:
            <<: *speed_template
            title: 90C
            smin: 100
          st100:
            <<: *speed_template
            title: 100C
            smin: 100

          enforce_limits:
            title: Enforce Windows Minimums
            type: bool
            default: True
            hint: >-
              Enforce the minimum fan curve from Legion Space.
            
          reset:
            title: Restore Default
            type: action
            hint: >-
              Resets to the original fan curve provided by Lenovo in BIOS V28.

  power_light:
    tags: [advanced]
    type: bool
    title: Enable Power Light
