type: container
title: General Settings
tags: [ advanced ]
children:
  enable:
    title: Enable TDP Controls
    type: bool
    default: False

  enforce_limits:
    title: Enforce Device Limits
    type: bool
    default: True

  error:
    title: Error
    type: display
    tags: [error]
    options: 
      nowrite: Can not write to ACPI Call file. ACPI Call is required for TDP.